package com.swing;


import com.bean.Bean;
import com.desk.Code;
import com.read.Use;
import com.sql.Shuju;
import com.sqlsession.Getsql;
import org.apache.ibatis.session.SqlSession;

import org.springframework.beans.factory.BeanFactory;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;

public class ZouMian {
    private JPanel zhongbu;

    private static JCheckBox qingkong;
    private static JCheckBox qingkongwen;
    private static JCheckBox zhiding;
    private JButton shuaixing;
    private  JPanel panel1;
    private ButtonGroup buttonGroup;
    private  JPanel panel2;
    private static JFrame frame;
    public ZouMian(){
        zhiding.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (zhiding.isSelected()){
                    frame.setAlwaysOnTop(true);
                }else {
                    frame.setAlwaysOnTop(false);
                }

            }
        });
        shuaixing.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                SqlSession getsql = Getsql.geSession();
                final Shuju shuju = getsql.getMapper(Shuju.class);
                panel1.removeAll();
                Use use = getUse();
                use.read();
                List<Bean> beans = shuju.selectall();
                JRadioButton jRadioButton[] = new JRadioButton[beans.size()];
                for (int i = 0; i <beans.size(); i++) {
                    final String name = beans.get(i).getName();
                    jRadioButton[i] = new JRadioButton(name);
                    jRadioButton[i].addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            JRadioButton temp = (JRadioButton) e.getSource();
                            String dizhi =temp.getText();
                            dizhi = shuju.select(dizhi);
                            Code code = Code.getCode();
                            code.setSysClipboardText(dizhi);
                        }
                    });
                    jRadioButton[i].setFont(new Font("宋体", Font.PLAIN, 16));
                    panel1.add(jRadioButton[i]);
                    buttonGroup.add(jRadioButton[i]);

                }

                zhongbu.validate();
                zhongbu.repaint();
            }


        });



    }

    private static Use getUse(){
        BeanFactory factory = new ClassPathXmlApplicationContext("Opera.xml");
        Use use = (Use) factory.getBean("useOperating");
        return use;
    }

    public static void main() {
        final SqlSession getsql = Getsql.geSession();
        frame = new JFrame("ZouMian");
        frame.setContentPane(new ZouMian().zhongbu);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setSize(400,300);

        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {

                Shuju shuju = getsql.getMapper(Shuju.class);
                if (qingkong.isSelected())
                {
                    shuju.delectall();
                    getsql.commit();

                }

                if(qingkongwen.isSelected()){
                    Use use = getUse();
                    use.qing();
                }
                getsql.close();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        zhongbu = new JPanel();
        zhongbu.setLayout(new BorderLayout(0, 0));
        qingkong = new JCheckBox("清空数据库");
        qingkongwen = new JCheckBox("清空表格");
        zhiding = new JCheckBox("置顶");
        panel2 = new JPanel();
        panel2.add(zhiding);
        panel2.add(qingkong);
        panel2.add(qingkongwen);
        zhongbu.add(panel2,BorderLayout.NORTH);
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT));
        zhongbu.add(panel1, BorderLayout.CENTER);
        shuaixing = new JButton("添加");
        zhongbu.add(shuaixing,BorderLayout.SOUTH);
        buttonGroup = new ButtonGroup();

    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return zhongbu;
    }
}
